SEQUENCE @startuml

Participant A
Participant B
Participant C
Participant D

ACTIVATE A
A -> B : POST "/hello"  waitingTime=1000
ACTIVATE B
B -> C : GET "/hello/ref"
alt "true"
    C -> B : 200
else "false"
    C -> B : 400
end
ACTIVATE C
DEACTIVATE C
B -> A : 200
DEACTIVATE B
A -> C : GET "/bye"
ACTIVATE C
alt "true"
    C -> A : 200
else "false"
    C -> A : 400
end
C -> A : POST "/bye"
alt "false"
    A -> C : 200
else "true"
    A -> C : 400
end
DEACTIVATE C
D -> A : GET "/quetal"
ACTIVATE D
A -> D : 200
DEACTIVATE D
DEACTIVATE A

@enduml